- name: install nginx server
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
    - name: install nginx
      state: present
  -name: start nginx
    ansible.builtin.service:
  - name: nginx
      state: started