- name: play1 
  hosts: web
  tasks:
  - name: play1
    ansible.builtin.debug:
      msg: "hello from play1"

- name: play2
  hosts: localhost
  tasks:
  - name: play2
    ansible.builtin.debug:
      msg: "hello from play2"
 
 
