- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "07:15AM IST"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}. Timings are: {{timings}}"
##keep in mind that we can use variables in inventory file . it search automatically in inventory and execute 
      
      
### this is how we store varaibles in inventory file 
#[localhost:vars]
#Course="DevOps with AWS"
#Trainer="Sivakumar"
#Duration="120hrs"
#WISHES="Morning from inventory"
