- name: declaring the variable
  hosts: localhost
  become: yes
  vars:
    name: "vijay"
    from: "amp"
    age: 25
  tasks:
  - name: declaring and assigning the value
    ansible.builtin.debug:
      msg: "my  name is {{name}} i am {{from}} i age is {{age}} "